<?php
/**
 * Created by PhpStorm.
 * User: Denis
 * Date: 11/27/16
 * Time: 11:58
 */

namespace common\components\constants;

use yii2mod\helpers\ArrayHelper;

class Constants
{
    public static $countries = [
        ['country' => "Afghanistan", 'flag' => "af flag"],
        ['country' => "Aland Islands", 'flag' => "ax flag"],
        ['country' => "Albania", 'flag' => "al flag"],
        ['country' => "Algeria", 'flag' => "dz flag"],
        ['country' => "American Samoa", 'flag' => "as flag"],
        ['country' => "Andorra", 'flag' => "ad flag"],
        ['country' => "Angola", 'flag' => "ao flag"],
        ['country' => "Anguilla", 'flag' => "ai flag"],
        ['country' => "Antigua", 'flag' => "ag flag"],
        ['country' => "Argentina", 'flag' => "ar flag"],
        ['country' => "Armenia", 'flag' => "am flag"],
        ['country' => "Aruba", 'flag' => "aw flag"],
        ['country' => "Australia", 'flag' => "au flag"],
        ['country' => "Austria", 'flag' => "at flag"],
        ['country' => "Azerbaijan", 'flag' => "az flag"],
        ['country' => "Bahamas", 'flag' => "bs flag"],
        ['country' => "Bahrain", 'flag' => "bh flag"],
        ['country' => "Bangladesh", 'flag' => "bd flag"],
        ['country' => "Barbados", 'flag' => "bb flag"],
        ['country' => "Belarus", 'flag' => "by flag"],
        ['country' => "Belgium", 'flag' => "be flag"],
        ['country' => "Belize", 'flag' => "bz flag"],
        ['country' => "Benin", 'flag' => "bj flag"],
        ['country' => "Bermuda", 'flag' => "bm flag"],
        ['country' => "Bhutan", 'flag' => "bt flag"],
        ['country' => "Bolivia", 'flag' => "bo flag"],
        ['country' => "Bosnia", 'flag' => "ba flag"],
        ['country' => "Botswana", 'flag' => "bw flag"],
        ['country' => "Bouvet Island", 'flag' => "bv flag"],
        ['country' => "Brazil", 'flag' => "br flag"],
        ['country' => "British Virgin Islands", 'flag' => "vg flag"],
        ['country' => "Brunei", 'flag' => "bn flag"],
        ['country' => "Bulgaria", 'flag' => "bg flag"],
        ['country' => "Burkina Faso", 'flag' => "bf flag"],
        ['country' => "Burma", 'flag' => "ar flag"],
        ['country' => "Burundi", 'flag' => "bi flag"],
        ['country' => "Caicos Islands", 'flag' => "tc flag"],
        ['country' => "Cambodia", 'flag' => "kh flag"],
        ['country' => "Cameroon", 'flag' => "cm flag"],
        ['country' => "Canada", 'flag' => "ca flag"],
        ['country' => "Cape Verde", 'flag' => "cv flag"],
        ['country' => "Cayman Islands", 'flag' => "ky flag"],
        ['country' => "Central African Republic", 'flag' => "cf flag"],
        ['country' => "Chad", 'flag' => "td flag"],
        ['country' => "Chile", 'flag' => "cl flag"],
        ['country' => "China", 'flag' => "cn flag"],
        ['country' => "Christmas Island", 'flag' => "cx flag"],
        ['country' => "Cocos Islands", 'flag' => "cc flag"],
        ['country' => "Colombia", 'flag' => "co flag"],
        ['country' => "Comoros", 'flag' => "km flag"],
        ['country' => "Congo Brazzaville", 'flag' => "cg flag"],
        ['country' => "Congo", 'flag' => "cd flag"],
        ['country' => "Cook Islands", 'flag' => "ck flag"],
        ['country' => "Costa Rica", 'flag' => "cr flag"],
        ['country' => "Cote Divoire", 'flag' => "ci flag"],
        ['country' => "Croatia", 'flag' => "hr flag"],
        ['country' => "Cuba", 'flag' => "cu flag"],
        ['country' => "Cyprus", 'flag' => "cy flag"],
        ['country' => "Czech Republic", 'flag' => "cz flag"],
        ['country' => "Denmark", 'flag' => "dk flag"],
        ['country' => "Djibouti", 'flag' => "dj flag"],
        ['country' => "Dominica", 'flag' => "dm flag"],
        ['country' => "Dominican Republic", 'flag' => "do flag"],
        ['country' => "Ecuador", 'flag' => "ec flag"],
        ['country' => "Egypt", 'flag' => "eg flag"],
        ['country' => "El Salvador", 'flag' => "sv flag"],
        ['country' => "England", 'flag' => "gb flag"],
        ['country' => "Equatorial Guinea", 'flag' => "gq flag"],
        ['country' => "Eritrea", 'flag' => "er flag"],
        ['country' => "Estonia", 'flag' => "ee flag"],
        ['country' => "Ethiopia", 'flag' => "et flag"],
        ['country' => "European Union", 'flag' => "eu flag"],
        ['country' => "Falkland Islands", 'flag' => "fk flag"],
        ['country' => "Faroe Islands", 'flag' => "fo flag"],
        ['country' => "Fiji", 'flag' => "fj flag"],
        ['country' => "Finland", 'flag' => "fi flag"],
        ['country' => "France", 'flag' => "fr flag"],
        ['country' => "French Guiana", 'flag' => "gf flag"],
        ['country' => "French Polynesia", 'flag' => "pf flag"],
        ['country' => "French Territories", 'flag' => "tf flag"],
        ['country' => "Gabon", 'flag' => "ga flag"],
        ['country' => "Gambia", 'flag' => "gm flag"],
        ['country' => "Georgia", 'flag' => "ge flag"],
        ['country' => "Germany", 'flag' => "de flag"],
        ['country' => "Ghana", 'flag' => "gh flag"],
        ['country' => "Gibraltar", 'flag' => "gi flag"],
        ['country' => "Greece", 'flag' => "gr flag"],
        ['country' => "Greenland", 'flag' => "gl flag"],
        ['country' => "Grenada", 'flag' => "gd flag"],
        ['country' => "Guadeloupe", 'flag' => "gp flag"],
        ['country' => "Guam", 'flag' => "gu flag"],
        ['country' => "Guatemala", 'flag' => "gt flag"],
        ['country' => "Guinea-Bissau", 'flag' => "gw flag"],
        ['country' => "Guinea", 'flag' => "gn flag"],
        ['country' => "Guyana", 'flag' => "gy flag"],
        ['country' => "Haiti", 'flag' => "ht flag"],
        ['country' => "Heard Island", 'flag' => "hm flag"],
        ['country' => "Honduras", 'flag' => "hn flag"],
        ['country' => "Hong Kong", 'flag' => "hk flag"],
        ['country' => "Hungary", 'flag' => "hu flag"],
        ['country' => "Iceland", 'flag' => "is flag"],
        ['country' => "India", 'flag' => "in flag"],
        ['country' => "Indian Ocean Territory", 'flag' => "io flag"],
        ['country' => "Indonesia", 'flag' => "id flag"],
        ['country' => "Iran", 'flag' => "ir flag"],
        ['country' => "Iraq", 'flag' => "iq flag"],
        ['country' => "Ireland", 'flag' => "ie flag"],
        ['country' => "Israel", 'flag' => "il flag"],
        ['country' => "Italy", 'flag' => "it flag"],
        ['country' => "Jamaica", 'flag' => "jm flag"],
        ['country' => "Japan", 'flag' => "jp flag"],
        ['country' => "Jordan", 'flag' => "jo flag"],
        ['country' => "Kazakhstan", 'flag' => "kz flag"],
        ['country' => "Kenya", 'flag' => "ke flag"],
        ['country' => "Kiribati", 'flag' => "ki flag"],
        ['country' => "Kuwait", 'flag' => "kw flag"],
        ['country' => "Kyrgyzstan", 'flag' => "kg flag"],
        ['country' => "Laos", 'flag' => "la flag"],
        ['country' => "Latvia", 'flag' => "lv flag"],
        ['country' => "Lebanon", 'flag' => "lb flag"],
        ['country' => "Lesotho", 'flag' => "ls flag"],
        ['country' => "Liberia", 'flag' => "lr flag"],
        ['country' => "Libya", 'flag' => "ly flag"],
        ['country' => "Liechtenstein", 'flag' => "li flag"],
        ['country' => "Lithuania", 'flag' => "lt flag"],
        ['country' => "Luxembourg", 'flag' => "lu flag"],
        ['country' => "Macau", 'flag' => "mo flag"],
        ['country' => "Macedonia", 'flag' => "mk flag"],
        ['country' => "Madagascar", 'flag' => "mg flag"],
        ['country' => "Malawi", 'flag' => "mw flag"],
        ['country' => "Malaysia", 'flag' => "my flag"],
        ['country' => "Maldives", 'flag' => "mv flag"],
        ['country' => "Mali", 'flag' => "ml flag"],
        ['country' => "Malta", 'flag' => "mt flag"],
        ['country' => "Marshall Islands", 'flag' => "mh flag"],
        ['country' => "Martinique", 'flag' => "mq flag"],
        ['country' => "Mauritania", 'flag' => "mr flag"],
        ['country' => "Mauritius", 'flag' => "mu flag"],
        ['country' => "Mayotte", 'flag' => "yt flag"],
        ['country' => "Mexico", 'flag' => "mx flag"],
        ['country' => "Micronesia", 'flag' => "fm flag"],
        ['country' => "Moldova", 'flag' => "md flag"],
        ['country' => "Monaco", 'flag' => "mc flag"],
        ['country' => "Mongolia", 'flag' => "mn flag"],
        ['country' => "Montenegro", 'flag' => "me flag"],
        ['country' => "Montserrat", 'flag' => "ms flag"],
        ['country' => "Morocco", 'flag' => "ma flag"],
        ['country' => "Mozambique", 'flag' => "mz flag"],
        ['country' => "Namibia", 'flag' => "na flag"],
        ['country' => "Nauru", 'flag' => "nr flag"],
        ['country' => "Nepal", 'flag' => "np flag"],
        ['country' => "Netherlands Antilles", 'flag' => "an flag"],
        ['country' => "Netherlands", 'flag' => "nl flag"],
        ['country' => "New Caledonia", 'flag' => "nc flag"],
        ['country' => "New Guinea", 'flag' => "pg flag"],
        ['country' => "New Zealand", 'flag' => "nz flag"],
        ['country' => "Nicaragua", 'flag' => "ni flag"],
        ['country' => "Niger", 'flag' => "ne flag"],
        ['country' => "Nigeria", 'flag' => "ng flag"],
        ['country' => "Niue", 'flag' => "nu flag"],
        ['country' => "Norfolk Island", 'flag' => "nf flag"],
        ['country' => "North Korea", 'flag' => "kp flag"],
        ['country' => "Northern Mariana Islands", 'flag' => "mp flag"],
        ['country' => "Norway", 'flag' => "no flag"],
        ['country' => "Oman", 'flag' => "om flag"],
        ['country' => "Pakistan", 'flag' => "pk flag"],
        ['country' => "Palau", 'flag' => "pw flag"],
        ['country' => "Palestine", 'flag' => "ps flag"],
        ['country' => "Panama", 'flag' => "pa flag"],
        ['country' => "Paraguay", 'flag' => "py flag"],
        ['country' => "Peru", 'flag' => "pe flag"],
        ['country' => "Philippines", 'flag' => "ph flag"],
        ['country' => "Pitcairn Islands", 'flag' => "pn flag"],
        ['country' => "Poland", 'flag' => "pl flag"],
        ['country' => "Portugal", 'flag' => "pt flag"],
        ['country' => "Puerto Rico", 'flag' => "pr flag"],
        ['country' => "Qatar", 'flag' => "qa flag"],
        ['country' => "Reunion", 'flag' => "re flag"],
        ['country' => "Romania", 'flag' => "ro flag"],
        ['country' => "Russia", 'flag' => "ru flag"],
        ['country' => "Rwanda", 'flag' => "rw flag"],
        ['country' => "Saint Helena", 'flag' => "sh flag"],
        ['country' => "Saint Kitts and Nevis", 'flag' => "kn flag"],
        ['country' => "Saint Lucia", 'flag' => "lc flag"],
        ['country' => "Saint Pierre", 'flag' => "pm flag"],
        ['country' => "Saint Vincent", 'flag' => "vc flag"],
        ['country' => "Samoa", 'flag' => "ws flag"],
        ['country' => "San Marino", 'flag' => "sm flag"],
        ['country' => "Sandwich Islands", 'flag' => "gs flag"],
        ['country' => "Sao Tome", 'flag' => "st flag"],
        ['country' => "Saudi Arabia", 'flag' => "sa flag"],
        ['country' => "Senegal", 'flag' => "sn flag"],
        ['country' => "Serbia", 'flag' => "cs flag"],
        ['country' => "Serbia", 'flag' => "rs flag"],
        ['country' => "Seychelles", 'flag' => "sc flag"],
        ['country' => "Sierra Leone", 'flag' => "sl flag"],
        ['country' => "Singapore", 'flag' => "sg flag"],
        ['country' => "Slovakia", 'flag' => "sk flag"],
        ['country' => "Slovenia", 'flag' => "si flag"],
        ['country' => "Solomon Islands", 'flag' => "sb flag"],
        ['country' => "Somalia", 'flag' => "so flag"],
        ['country' => "South Africa", 'flag' => "za flag"],
        ['country' => "South Korea", 'flag' => "kr flag"],
        ['country' => "Spain", 'flag' => "es flag"],
        ['country' => "Sri Lanka", 'flag' => "lk flag"],
        ['country' => "Sudan", 'flag' => "sd flag"],
        ['country' => "Suriname", 'flag' => "sr flag"],
        ['country' => "Svalbard", 'flag' => "sj flag"],
        ['country' => "Swaziland", 'flag' => "sz flag"],
        ['country' => "Sweden", 'flag' => "se flag"],
        ['country' => "Switzerland", 'flag' => "ch flag"],
        ['country' => "Syria", 'flag' => "sy flag"],
        ['country' => "Taiwan", 'flag' => "tw flag"],
        ['country' => "Tajikistan", 'flag' => "tj flag"],
        ['country' => "Tanzania", 'flag' => "tz flag"],
        ['country' => "Thailand", 'flag' => "th flag"],
        ['country' => "Timorleste", 'flag' => "tl flag"],
        ['country' => "Togo", 'flag' => "tg flag"],
        ['country' => "Tokelau", 'flag' => "tk flag"],
        ['country' => "Tonga", 'flag' => "to flag"],
        ['country' => "Trinidad", 'flag' => "tt flag"],
        ['country' => "Tunisia", 'flag' => "tn flag"],
        ['country' => "Turkey", 'flag' => "tr flag"],
        ['country' => "Turkmenistan", 'flag' => "tm flag"],
        ['country' => "Tuvalu", 'flag' => "tv flag"],
        ['country' => "Uganda", 'flag' => "ug flag"],
        ['country' => "Ukraine", 'flag' => "ua flag"],
        ['country' => "United Arab Emirates", 'flag' => "ae flag"],
        ['country' => "United States", 'flag' => "us flag"],
        ['country' => "Uruguay", 'flag' => "uy flag"],
        ['country' => "Us Minor Islands", 'flag' => "um flag"],
        ['country' => "Us Virgin Islands", 'flag' => "vi flag"],
        ['country' => "Uzbekistan", 'flag' => "uz flag"],
        ['country' => "Vanuatu", 'flag' => "vu flag"],
        ['country' => "Vatican City", 'flag' => "va flag"],
        ['country' => "Venezuela", 'flag' => "ve flag"],
        ['country' => "Vietnam", 'flag' => "vn flag"],
        ['country' => "Wallis and Futuna", 'flag' => "wf flag"],
        ['country' => "Western Sahara", 'flag' => "eh flag"],
        ['country' => "Yemen", 'flag' => "ye flag"],
        ['country' => "Zambia", 'flag' => "zm flag"],
        ['country' => "Zimbabwe", 'flag' => "zw flag"],
    ];


    public static function getCountryFlag($country)
    {
        $flag = self::$countries[array_search($country,
            array_map(function ($element) { return $element['country']; }, self::$countries))]['flag'];

        return $flag;
    }


    public static function getCountryFlagHtml($country)
    {
        return '<i class="' . self::getCountryFlag($country) . '"></i>';
    }


    public static function isInCountryList($country)
    {
        $some = ArrayHelper::getColumn(self::$countries, 'country');

        return in_array($country, $some);
    }
}